application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /styles
  static_dir: styles

- url: /javascript
  static_dir: javascript
#new handlers should go ABOVE the catch all url (.*)
- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
